services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - leaderboard-api-network
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - leaderboard-api-network
    depends_on:
      - mongo
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
    networks:
      - leaderboard-api-network
  redis-insight:
    image: redis/redisinsight:2.60
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - ./redis-insight:/data
    networks:
      - leaderboard-api-network

networks:
  leaderboard-api-network:
    driver: bridge
